version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: education
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build:
      context: ./user
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=education
    depends_on:
      - postgres
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - USER_SERVICE_URL=http://user-service:3000
      - USER_SERVICE_HOST=user-service
      - USER_SERVICE_PORT=3000
    networks:
      - microservices-network
    depends_on:
      user-service:
        condition: service_healthy

networks:
  microservices-network:
    driver: bridge

volumes:
  postgres_data:
